### ISSUE TITLE
get it working with nut

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/golang-vscode#2]
Docker Nut: the development environment, containerized.
http://matthieudelaro.github.io/nut/

cc @matthieudelaro

**Comment by matthieudelaro** [comment]
Hi @ctaggart,

Does your script `run-dockerformac.sh` work?

``` bash
#!/bin/sh
open -a XQuartz
xhost + # TODO limit to just the host
# bridge100 is disappearing after a reboot
ip=`ifconfig bridge100 | grep inet | awk '$1=="inet" {print $2}'`
docker run --rm -it -w /root -e DISPLAY=$ip:0 ctaggart/golang-vscode
```

I'm using Docker for Mac, but your script does not open any window for me.

**Comment by ctaggart** [comment]
@matthieudelaro See #1 where I documented it. After launching the docker, run `./start-vscode.sh`. Also, I need to add all the go dependencies #3, but you should be able to launch vscode and see that the `go` extension is installed.

**Comment by matthieudelaro** [comment]
Ok, I found the issue. I thing that `xhost +` doesn't make any effect on my Mac. So I use nut to forward connection, and then I can open vscode. I'll look at the nut file soon.

**Comment by matthieudelaro** [comment]
Done :)
[PR #4](https://github.com/ctaggart/golang-vscode/pull/4)

=> `nut run`

**Comment by matthieudelaro** [comment]
You can adapt the section `mount` in the `nut.yml` if you wish to mount some folders:

``` yml
mount:
  main:
    - ./root
    - /root
  code:
    - ./code
    - /home/vscode
```

**Comment by ctaggart** [comment]
This is really awesome! It is working, although I'm troubleshooting some OSX panics when using it. I set it up so that `nut code` allows me to edit this project. I'll probably add a git submodule and add a `nut test` that allows me to see that the Go editing is actually working. Thanks for the great work on nut!

**Comment by matthieudelaro** [comment]
Glad you like it :)
What OSX panic do you get? I did not experience any.
