### ISSUE TITLE
support vendor directories

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/golang-vscode#6]
[Go 1.6](https://golang.org/doc/go1.6) enabled [vendoring](https://golang.org/cmd/go/#hdr-Vendor_Directories) by default. Project like [nut](http://matthieudelaro.github.io/nut/) use it by putting all of the dependencies in a subdirectory named `vendor` via git submodules. One or more of the [go dependencies](https://github.com/ctaggart/golang-vscode/blob/master/root/install-vscode-Go.sh#L11-L19) doesn't appear to support it. I'm not sure which one does the imports.

![image](https://cloud.githubusercontent.com/assets/80104/14905585/fa749982-0d66-11e6-9613-9f8da30c6254.png)
- is it support vendor? #162 https://github.com/Microsoft/vscode-go/issues/162
- VS Code workspace settings `.vscode/settings.json` `go.gopath`.
  `Specifies the GOPATH to use when no environment variable is set.`
  I can only get the environment variable to work. https://github.com/Microsoft/vscode-go/issues/185
## workaround

My workaround is to make it look like a workspace by setting `GOPATH` to the current directory and using symlinks.

```
ln -s vendor src
mkdir -p vendor/github.com/matthieudelaro/nut
ln -s `pwd`/persist `pwd`/vendor/github.com/matthieudelaro/nut/persist
export GOPATH=`pwd`; code .
```

**Comment by matthieudelaro** [comment]
I think vendor support has been introduced in Go 1.6, and maybe this is not the version in use in the editor?

If you want to use vendor with version 1.5, you have to set a certain flag at compilation, and/or add the vendor folder in the Go path. But the trick is that Go 1.5 expects dependencies to be in `thePathToYourVendor/src/github....`, not in `thePathToYourVendor/github....`, so if you want to give it a try, you may copy-paste or move vendor to vendor/src

**Comment by ctaggart** [comment]
It turned out that vendor directories works just fine if it in within a directory that is on the GOPATH. This is not an issue with Go 1.6 on the image I created. Yay!
